### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by strugee** [yeoman/yosay#28]
This project could use a proper change log. I sent #27, but that isn't really ideal since GitHub release notes don't seem to be kept up-to-date.

See http://keepachangelog.com

**Comment by sindresorhus** [comment]
Read the commit log. A changelog wouldn't provide any more information: https://github.com/yeoman/yosay/commits/master

**Comment by strugee** [comment]
@sindresorhus the problem with that is that there's a lot of noise.

**Comment by mischah** [comment]
There is not that much noise since commits are squashed before landing in master branch. 

See this for example:
https://github.com/yeoman/yosay/pull/24/

**Comment by strugee** [comment]
Commit squashing isn't the issue and in fact makes things worse - d56182d992b6a2f1f4c3d9717adb3081a1909166 is a great example of this because the commit isn't atomic and so you have to actually open up the commit description to find out what it does instead of being able to just read the log.

Here's some recent commits that have zero bearing on me as a consumer: 00c279fd1f02aaeaf3b3bd76f07c8114beae977b, 1614e0adc24d9f3e59583bbb991ea844f322d39f, a5957de8b585ed5134c1c5412a8a6e373bc99cb0 (note that this one also contains a change completely unrelated to the commit message - if that was a functional change I probably would've just missed it!), ed13351f91f3bd32a9b0f0b1f28546b159c7f35f, 534b8f388728d9921707cbc610e7ef53ff611da9, and 1e97b3488450e4d5207aa428cfe3c154d4681cff. All of those are noise.

Quoting http://keepachangelog.com, which I already linked to:

> **Why can’t people just use a `git log` diff?**
>
> Because log diffs are full of noise — by nature. They could not make a suitable change log even in a hypothetical project run by perfect humans who never make typos, never forget to commit new files, never miss any part of a refactoring. The purpose of a commit is to document one atomic step in the process by which the code evolves from one state to another. The purpose of a change log is to document the noteworthy differences between these states.
>
> As is the difference between good comments and the code itself, so is the difference between a change log and the commit log: one describes the why, the other the how.

**Comment by mischah** [comment]
Don’t feel your arguments/examples. But I feel the need to see (at least) breaking changes. 

To make that easier I’m going to try to keep Github releases in sync with npm releases.
… Just »published« v2.0.0 over here: https://github.com/yeoman/yosay/releases 😘
