### ISSUE TITLE
Too long words went broken with colors

### ISSUE THREAD

**Issue by motss** [yeoman/yosay#29]
## Code snippet:

```js
const chalk = require('chalk');
const yosay = require('yosay');

const toBeColored = 'something iloveunicornsiloveunicornsiloveunicornsiloveunicornsiloveunicornsiloveunicorns';
const str = `Welcome to the polished ${chalk.red(toBeColored)} generator!`;

console.log(yosay(str));
```

## Actual result:

`rns` is not in red color.

<img width="352" alt="screen shot 2017-03-28 at 4 07 38 pm" src="https://cloud.githubusercontent.com/assets/10607759/24395234/8d0ba382-13d1-11e7-97c2-f999b95c6cbd.png">

## Expected result

Colored sentences should always be in the defined color.

**Comment by mischah** [comment]
Can replicate that with Node 6.9.5 on OS X
