### ISSUE TITLE
Add support for custom Yeoman character

### ISSUE THREAD

**Issue by oscarmarcelo** [yeoman/yosay#33]
Hey! 👋 
Do you guys have plans to add an option to customize the Yeoman character?

Something like providing a string with `\n` (like you already have) or an array with the lines, and the character width would be defined by the widest line. The smaller ones would be padded internally to match their width.

I would be happy to send a PR. 🙂

**Comment by sindresorhus** [comment]
What character do you have in mind?

**Comment by oscarmarcelo** [comment]
I could be anything.

For example, I'm working on a Yeoman [generator](/oscarmarcelo/bengal) that has a cat as brand mascot, and I though it would be cool if I could replace the yeoman face with the mascot face.

**Comment by sindresorhus** [comment]
Alright. PR welcome. But the code is quite complex. You’ve been warned. It’s gonna need a lot of tests.
