### ISSUE TITLE
Cut a new release to solve security issues in dependency chains

### ISSUE THREAD

**Issue by vpetkar** [yeoman/yosay#34]
There are [security vulnerabilities](https://security.snyk.io/vuln/SNYK-JS-ANSIREGEX-1583908) in ansi-regex <3.0.0. It appears that this has already been fixed on master, so all that is required is cutting a new release to npm.

**Comment by Dylanlan** [comment]
We'd also be interested in this - we're running into the same vulnerability warning from Snyk.

We have considered trying to use a Yarn Resolution to indirectly upgrade the ansi-regex version that gets used: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

I'd be nice to just use a new version of this package instead, though.
